name: Lint frontend

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**/package.json'
      - 'CHANGELOG.md'
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  lint-frontend:
    name: Run frontend linters
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
            node-version: 24

      - name: Install Node.js dependencies
        working-directory: frontend
        run: |
          npm install

      - name: Run linters
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          workdir: frontend
          eslint_flags: "--format rdjson --ext .js,.jsx,.ts,.tsx ./"
          fail_level: error
