name: Lint backend

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.py'
      - 'CHANGELOG.md'
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  lint-backend:
    name: Run backend linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
