name: AI-assisted
on:
  pull_request:
    types: [ready_for_review, opened, reopened]

jobs:
  approve:
    name: Approve
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.head.repo.fork == true && 'manual-approval' || '' }}

  summary:
    name: PR Summary
    needs: approve
    if: github.actor != 'dependabot[bot]'
    runs-on: [ubuntu-latest]
    steps:
      - uses: SAP/ai-assisted-github-actions/pr-summary@v3
        with:
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          model: gpt-4.1-nano
          exclude-files: package-lock.json, uv.lock
  review:
    name: PR Review
    needs: approve
    if: github.actor != 'dependabot[bot]'
    runs-on: [ubuntu-latest]
    steps:
      - uses: SAP/ai-assisted-github-actions/pr-review@v3
        with:
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          model: anthropic--claude-4.6-sonnet
          exclude-files: package-lock.json, uv.lock
          footer-text: |
            ---
            > Always critique what AI says. Do not let AI replace YOUR I.
          prompt-addition: |
            Do not feel obliged to comment on every file. Focus on the most important aspects of the code change.
            Keep your comments concise and to the point.
            Avoid unnecessary complexity, and focus on maintainability, readability, and performance.
